services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  subscriber:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    depends_on:
      - redis
    stdin_open: true
    tty: true

  publisher:
    build:
      context: .
      dockerfile: Dockerfile.publisher
    depends_on:
      - redis
    stdin_open: true
    tty: true